name: Publish on tag

on:
  push:
    tags:
      - '*'

env:
  JAVA_VERSION: 17
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Get tag name
        uses: olegtarasov/get-tag@v2.1.2
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: 检查环境变量
        run: env

      - name: 签出存储库
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: 设置 Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{env.JAVA_VERSION}}

      - name: 构建
        run: ./gradlew :jar

      - name: 发布（CurseForge/Modrinth/Github）
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          curseforge-id: 483760
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"

          modrinth-id: WMDesFsZ
          modrinth-token: "${{env.MODRINTH_TOKEN}}"

          github-token: "${{env.GITHUB_TOKEN}}"

          name: "mymodid-${{env.GIT_TAG_NAME}}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric, forge
          game-versions: "${{ steps.branch-name.outputs.current_branch }}"
          java: "${{env.JAVA_VERSION}}"
